
import { GameLevel } from './types';

export const GAME_LEVELS: GameLevel[] = [
  {
    levelNumber: 1,
    grade: "一年级 (上)",
    poemTitle: "悯农",
    poemAuthor: "李绅",
    fullLine: "谁知盘中餐，粒粒皆辛苦。",
    meaning: "有谁知道碗里的米饭，每一粒都是农民辛辛苦苦种出来的呢？",
    fullPoem: ["锄禾日当午，", "汗滴禾下土。", "谁知盘中餐，", "粒粒皆辛苦。"],
    pairs: [
      { id: "1-1", result: "谁", parts: ["讠", "隹"], solved: false },
      { id: "1-2", result: "知", parts: ["矢", "口"], solved: false },
      { id: "1-3", result: "粒", parts: ["米", "立"], solved: false },
      { id: "1-4", result: "辛", parts: ["立", "十"], solved: false },
      { id: "1-5", result: "苦", parts: ["艹", "古"], solved: false },
    ],
  },
  {
    levelNumber: 2,
    grade: "一年级 (下)",
    poemTitle: "静夜思",
    poemAuthor: "李白",
    fullLine: "低头思故乡。",
    meaning: "低下头沉思，不禁想起了远方的家乡。",
    fullPoem: ["床前明月光，", "疑是地上霜。", "举头望明月，", "低头思故乡。"],
    pairs: [
      { id: "2-1", result: "低", parts: ["亻", "氐"], solved: false },
      { id: "2-2", result: "头", parts: ["丶", "买"], solved: false },
      { id: "2-3", result: "思", parts: ["田", "心"], solved: false },
      { id: "2-4", result: "故", parts: ["古", "攵"], solved: false },
      { id: "2-5", result: "乡", parts: ["纟", "⺕"], solved: false },
    ],
  },
  {
    levelNumber: 3,
    grade: "二年级 (上)",
    poemTitle: "咏鹅",
    poemAuthor: "骆宾王",
    fullLine: "红掌拨清波。",
    meaning: "红红的脚掌在清澈的水波中拨动着。",
    fullPoem: ["鹅，鹅，鹅，", "曲项向天歌。", "白毛浮绿水，", "红掌拨清波。"],
    pairs: [
      { id: "3-1", result: "红", parts: ["纟", "工"], solved: false },
      { id: "3-2", result: "掌", parts: ["尚", "手"], solved: false },
      { id: "3-3", result: "拨", parts: ["扌", "发"], solved: false },
      { id: "3-4", result: "清", parts: ["氵", "青"], solved: false },
      { id: "3-5", result: "波", parts: ["氵", "皮"], solved: false },
    ],
  },
  {
    levelNumber: 4,
    grade: "二年级 (上)",
    poemTitle: "登鹳雀楼",
    poemAuthor: "王之涣",
    fullLine: "欲穷千里目，更上一层楼。",
    meaning: "如果想要看到更远处的风景，就要再往上爬一层楼。",
    fullPoem: ["白日依山尽，", "黄河入海流。", "欲穷千里目，", "更上一层楼。"],
    pairs: [
      { id: "4-1", result: "欲", parts: ["谷", "欠"], solved: false },
      { id: "4-2", result: "穷", parts: ["穴", "力"], solved: false },
      { id: "4-3", result: "更", parts: ["一", "由"], solved: false },
      { id: "4-4", result: "层", parts: ["尸", "云"], solved: false },
      { id: "4-5", result: "楼", parts: ["木", "娄"], solved: false },
    ],
  },
  {
    levelNumber: 5,
    grade: "二年级 (下)",
    poemTitle: "绝句",
    poemAuthor: "杜甫",
    fullLine: "窗含西岭千秋雪。",
    meaning: "窗户里正好映照着西岭上终年不化的积雪。",
    fullPoem: ["两个黄鹂鸣翠柳，", "一行白鹭上青天。", "窗含西岭千秋雪，", "门泊东吴万里船。"],
    pairs: [
      { id: "5-1", result: "窗", parts: ["穴", "囱"], solved: false },
      { id: "5-2", result: "含", parts: ["今", "口"], solved: false },
      { id: "5-3", result: "岭", parts: ["山", "令"], solved: false },
      { id: "5-4", result: "秋", parts: ["禾", "火"], solved: false },
      { id: "5-5", result: "雪", parts: ["雨", "彐"], solved: false },
    ],
  },
  {
    levelNumber: 6,
    grade: "二年级 (下)",
    poemTitle: "寻隐者不遇",
    poemAuthor: "贾岛",
    fullLine: "松下问童子。",
    meaning: "在苍翠的松树下，我询问那位修行的童子。",
    fullPoem: ["松下问童子，", "言师采药去。", "只在此山中，", "云深不知处。"],
    pairs: [
      { id: "6-1", result: "松", parts: ["木", "公"], solved: false },
      { id: "6-2", result: "下", parts: ["一", "卜"], solved: false },
      { id: "6-3", result: "问", parts: ["门", "口"], solved: false },
      { id: "6-4", result: "童", parts: ["立", "里"], solved: false },
      { id: "6-5", result: "子", parts: ["了", "一"], solved: false },
    ],
  },
  {
    levelNumber: 7,
    grade: "三年级 (上)",
    poemTitle: "望天门山",
    poemAuthor: "李白",
    fullLine: "孤帆一片日边来。",
    meaning: "一只孤独的小船从天边那红日的尽头缓缓驶来。",
    fullPoem: ["天门中断楚江开，", "碧水东流至此回。", "两岸青山相对出，", "孤帆一片日边来。"],
    pairs: [
      { id: "7-1", result: "孤", parts: ["子", "瓜"], solved: false },
      { id: "7-2", result: "帆", parts: ["巾", "凡"], solved: false },
      { id: "7-3", result: "片", parts: ["丿", "占"], solved: false },
      { id: "7-4", result: "日", parts: ["冂", "一"], solved: false },
      { id: "7-5", result: "来", parts: ["木", "米"], solved: false },
    ],
  },
  {
    levelNumber: 8,
    grade: "三年级 (上)",
    poemTitle: "九月九日忆山东兄弟",
    poemAuthor: "王维",
    fullLine: "独在异乡为异客。",
    meaning: "一个人独自在他乡生活，每逢佳节都感到自己是个异乡人。",
    fullPoem: ["独在异乡为异客，", "每逢佳节倍思亲。", "遥知兄弟登高处，", "遍插茱萸少一人。"],
    pairs: [
      { id: "8-1", result: "独", parts: ["犭", "虫"], solved: false },
      { id: "8-2", result: "在", parts: ["𠂇", "土"], solved: false },
      { id: "8-3", result: "异", parts: ["巳", "共"], solved: false },
      { id: "8-4", result: "客", parts: ["宀", "各"], solved: false },
      { id: "8-5", result: "佳", parts: ["亻", "圭"], solved: false },
    ],
  },
  {
    levelNumber: 9,
    grade: "三年级 (下)",
    poemTitle: "守株待兔",
    poemAuthor: "韩非子",
    fullLine: "兔走触株，折颈而死。",
    meaning: "野兔飞快跑来撞在树桩上，撞断了脖子死掉了。",
    fullPoem: ["宋人有耕者。", "田中有株。", "兔走触株，折颈而死。", "因释其耒而守株，冀复得兔。"],
    pairs: [
      { id: "9-1", result: "兔", parts: ["免", "丶"], solved: false },
      { id: "9-2", result: "触", parts: ["角", "虫"], solved: false },
      { id: "9-3", result: "株", parts: ["木", "朱"], solved: false },
      { id: "9-4", result: "折", parts: ["扌", "斤"], solved: false },
      { id: "9-5", result: "颈", parts: ["圣", "页"], solved: false },
    ],
  },
  {
    levelNumber: 10,
    grade: "三年级 (下)",
    poemTitle: "清明",
    poemAuthor: "杜牧",
    fullLine: "借问酒家何处有，牧童遥指杏花村。",
    meaning: "请问哪里有喝酒歇脚的小店呢？放牛的小孩笑着指了指远方的杏花村。",
    fullPoem: ["清明时节雨纷纷，", "路上行人欲断魂。", "借问酒家何处有，", "牧童遥指杏花村。"],
    pairs: [
      { id: "10-1", result: "借", parts: ["亻", "昔"], solved: false },
      { id: "10-2", result: "遥", parts: ["辶", "摇"], solved: false },
      { id: "10-3", result: "指", parts: ["扌", "旨"], solved: false },
      { id: "10-4", result: "杏", parts: ["木", "口"], solved: false },
      { id: "10-5", result: "村", parts: ["木", "寸"], solved: false },
    ],
  },
];
